# -*- coding: utf-8 -*-
"""neurona.3d

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XmJz2x87oNkcsTEu8AE7IiUwzzpTEzxW
"""

import plotly.graph_objects as go
import numpy as np

def create_3d_neuron_plot():
    """
    Genera y muestra una visualización 3D de las partes de una neurona.
    """
    # ----------------------------------------------------
    # 1. Definir las coordenadas de cada parte de la neurona
    # ----------------------------------------------------

    # Coordenadas del Soma (cuerpo central)
    soma_x = [0]
    soma_y = [0]
    soma_z = [0]
    soma_info = "Soma (Cuerpo Celular)<br>Procesa la información"

    # Coordenadas para las Dendritas (ramificaciones de entrada)
    dendrites_x = [0, -1, None, 0, 1, None, 0, 0, None, 0, 0]
    dendrites_y = [0, 0.5, None, 0, 0.5, None, 0, -0.5, None, 0, -1]
    dendrites_z = [0, 1, None, 0, 1, None, 0, 1, None, 0, 1]

    # Coordenadas para el Axón (ramificación de salida)
    axon_x = [0, 0, 0, 0, -1, None, 0, 1]
    axon_y = [0, -2, -2, -3, -4, None, -3, -4]
    axon_z = [0, 0, 0, 0, 0, None, 0, 0]

    # Coordenadas de las Terminales del Axón (puntos de salida)
    terminals_x = [0, -1, 1]
    terminals_y = [-4, -4, -4]
    terminals_z = [0, 0, 0]
    terminals_info = ["Terminales del Axón<br>Transmite la señal",
                      "Terminales del Axón<br>Transmite la señal",
                      "Terminales del Axón<br>Transmite la señal"]

    # ----------------------------------------------------
    # 2. Crear la figura 3D con Plotly
    # ----------------------------------------------------
    fig = go.Figure()

    # Añadir el Soma (cuerpo celular)
    fig.add_trace(go.Scatter3d(
        x=soma_x, y=soma_y, z=soma_z,
        mode='markers',
        marker=dict(size=15, color='orange', opacity=1),
        hovertext=soma_info,
        hoverinfo='text',
        name='Soma'
    ))

    # Añadir las Dendritas
    fig.add_trace(go.Scatter3d(
        x=dendrites_x, y=dendrites_y, z=dendrites_z,
        mode='lines',
        line=dict(color='blue', width=4),
        name='Dendritas',
        hoverinfo='skip'
    ))

    # Añadir el Axón
    fig.add_trace(go.Scatter3d(
        x=axon_x, y=axon_y, z=axon_z,
        mode='lines',
        line=dict(color='green', width=4),
        name='Axón',
        hoverinfo='skip'
    ))

    # Añadir las Terminales del Axón
    fig.add_trace(go.Scatter3d(
        x=terminals_x, y=terminals_y, z=terminals_z,
        mode='markers',
        marker=dict(size=8, color='red', opacity=1),
        hovertext=terminals_info,
        hoverinfo='text',
        name='Terminales del Axón'
    ))

    # ----------------------------------------------------
    # 3. Personalizar el diseño del gráfico
    # ----------------------------------------------------
    fig.update_layout(
        title='Modelo 3D de una Neurona',
        scene=dict(
            xaxis_title='',
            yaxis_title='',
            zaxis_title='',
            xaxis=dict(showgrid=False, zeroline=False, showticklabels=False),
            yaxis=dict(showgrid=False, zeroline=False, showticklabels=False),
            zaxis=dict(showgrid=False, zeroline=False, showticklabels=False),
            aspectmode='data'
        )
    )

    fig.show()
    fig.write_html("neurona_modelo_3d.html")

# ----------------------------------------------------
# 4. Explicación de las partes en el modelo 3D
# ----------------------------------------------------
print("--- Explicación de las partes de la neurona ---")
print("1. **Soma (Cuerpo Celular)**: El gran punto naranja en el centro. Es el núcleo de la neurona, donde se integra y procesa la información de las dendritas.")
print("2. **Dendritas**: Las líneas azules que se ramifican desde el soma. Actúan como receptores de entrada, captando señales de otras neuronas.")
print("3. **Axón**: La línea verde que se extiende desde el soma. Es el conducto de salida de la neurona, por donde se transmite la señal una vez que el soma la procesa.")
print("4. **Terminales del Axón**: Los puntos rojos al final del axón. Son los puntos de conexión (sinapsis) que transmiten la señal a las dendritas de las siguientes neuronas.")

# Llamar a la función para generar la visualización
create_3d_neuron_plot()

fig.write_html("neurona_modelo_3d.html")

import plotly.graph_objects as go
import numpy as np

def create_3d_neuron_plot():
    """
    Genera y devuelve el objeto de figura 3D de una neurona.
    """
    # ----------------------------------------------------
    # 1. Definir las coordenadas de cada parte de la neurona
    # ----------------------------------------------------

    # Coordenadas del Soma (cuerpo central)
    soma_x, soma_y, soma_z = [0], [0], [0]
    soma_info = "Soma (Cuerpo Celular)<br>Procesa la información"

    # Coordenadas para las Dendritas (ramificaciones de entrada)
    dendrites_x = [0, -1, None, 0, 1, None, 0, 0, None, 0, 0]
    dendrites_y = [0, 0.5, None, 0, 0.5, None, 0, -0.5, None, 0, -1]
    dendrites_z = [0, 1, None, 0, 1, None, 0, 1, None, 0, 1]

    # Coordenadas para el Axón (ramificación de salida)
    axon_x = [0, 0, 0, 0, -1, None, 0, 1]
    axon_y = [0, -2, -2, -3, -4, None, -3, -4]
    axon_z = [0, 0, 0, 0, 0, None, 0, 0]

    # Coordenadas de las Terminales del Axón (puntos de salida)
    terminals_x = [0, -1, 1]
    terminals_y = [-4, -4, -4]
    terminals_z = [0, 0, 0]
    terminals_info = ["Terminales del Axón<br>Transmite la señal",
                      "Terminales del Axón<br>Transmite la señal",
                      "Terminales del Axón<br>Transmite la señal"]

    # ----------------------------------------------------
    # 2. Crear la figura 3D con Plotly
    # ----------------------------------------------------
    fig = go.Figure()

    # Añadir las partes de la neurona
    fig.add_trace(go.Scatter3d(x=soma_x, y=soma_y, z=soma_z, mode='markers', marker=dict(size=15, color='orange', opacity=1), hovertext=soma_info, hoverinfo='text', name='Soma'))
    fig.add_trace(go.Scatter3d(x=dendrites_x, y=dendrites_y, z=dendrites_z, mode='lines', line=dict(color='blue', width=4), name='Dendritas', hoverinfo='skip'))
    fig.add_trace(go.Scatter3d(x=axon_x, y=axon_y, z=axon_z, mode='lines', line=dict(color='green', width=4), name='Axón', hoverinfo='skip'))
    fig.add_trace(go.Scatter3d(x=terminals_x, y=terminals_y, z=terminals_z, mode='markers', marker=dict(size=8, color='red', opacity=1), hovertext=terminals_info, hoverinfo='text', name='Terminales del Axón'))

    # Personalizar el diseño del gráfico
    fig.update_layout(
        title='Modelo 3D de una Neurona',
        scene=dict(
            xaxis_title='', yaxis_title='', zaxis_title='',
            xaxis=dict(showgrid=False, zeroline=False, showticklabels=False),
            yaxis=dict(showgrid=False, zeroline=False, showticklabels=False),
            zaxis=dict(showgrid=False, zeroline=False, showticklabels=False),
            aspectmode='data'
        )
    )

    # Devolver la figura para que se pueda usar fuera de la función
    return fig

# ----------------------------------------------------
# 3. Llamar a la función, mostrar y guardar la figura
# ----------------------------------------------------

# Llama a la función y guarda el resultado en la variable 'fig'
fig = create_3d_neuron_plot()

# Muestra el gráfico en la salida de Colab
fig.show()

# Guarda el gráfico como un archivo HTML para su uso posterior
fig.write_html("neurona_modelo_3d.html")